version: '3.8'

networks:
  eventsource-network:
    name: eventsource-network

services:

  zookeeper:
    container_name: zookeeper
    image: 'confluentinc/cp-zookeeper:5.5.0'
    networks:
      - eventsource-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ALLOW_ANONYMOUS_LOGIN: 'yes'
    deploy:
      resources:
        limits:
          memory: 200M

  broker:
    container_name: broker
    image: 'confluentinc/cp-kafka:5.5.0'
    networks:
      - eventsource-network
    ports:
      - '19092:19092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,CONNECTIONS_FROM_HOST://${LISTENER_HOST:-localhost:19092}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONNECTIONS_FROM_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    deploy:
      resources:
        limits:
          memory: 1G

