
filebeat.config:
  inputs:
    path: ${path.config}/inputs/*.yml
    reload.enabled: false

#============================= Filebeat modules ===============================

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

#==================== Elasticsearch template setting ==========================

setup.template.settings:
  index.number_of_shards: 3

#================================ General =====================================

#name:
#tags: ["service-X", "web-tier"]
#fields:
#  env: staging


#============================== Dashboards =====================================
#setup.dashboards.enabled: false
#setup.dashboards.url:

#============================== Kibana =====================================

setup.kibana:
  #host: "localhost:5601"
  #space.id:

#============================= Elastic Cloud ==================================
#cloud.id:
#cloud.auth:

#================================ Outputs =====================================
output.elasticsearch:
  hosts: [{{ elasticsearch_master_endpoints | join(', ')}}]

  #ilm.enabled: false

  #username: "elastic"
  #password: "changeme"

#================================ Processors =====================================

# Configure processors to enhance or manipulate events generated by the beat.
processors:
   - drop_fields:
       fields: ["beat.hostname", "beat.version", "beat.name", "log.file.path", "source", "prospector" ]
#  - add_host_metadata: ~
#  - add_cloud_metadata: ~

#================================ Logging =====================================

#logging.level: debug
#logging.selectors: ["*"]

#============================== Xpack Monitoring ===============================
#xpack.monitoring.enabled: false
#xpack.monitoring.elasticsearch:
